version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     build: .
     image: rafael/wordpress:1
     volumes:
       - wordpress_files:/var/www/html
     ports:
       - "8080:80"
     networks:
       - backend
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: teste1
   db:
     image: mysql:5.6
    # volumes:
    #   - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     networks:
       - backend
     environment:
       - MYSQL_ROOT_PASSWORD=teste1
       - MYSQL_DATABASE=wordpress

   jenkins:
     image: jenkinsci/blueocean:latest
     volumes:
       - jenkins_data:/var/jenkins_home
     ports:
       - "8081:8080"
       - "5000:5000"
       - "50000:50000"
     networks:
       - backend



volumes:
    wordpress_files:
    db_data:
    jenkins_data:
networks:
  backend:
    driver: bridge
